# Generated by: coq_makefile -f _CoqProject -o CoqMakefile
# Run `make init` once after setup to generate CoqMakefile

.PHONY: all clean init

init:
	coq_makefile -f _CoqProject -o CoqMakefile

all: CoqMakefile
	$(MAKE) -f CoqMakefile

clean: CoqMakefile
	$(MAKE) -f CoqMakefile clean

CoqMakefile:
	@echo "Run 'make init' first to generate CoqMakefile"
	@exit 1
